//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.Icargasql")]
    public interface Icargasql {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icargasql/guardar_datos", ReplyAction="http://tempuri.org/Icargasql/guardar_datosResponse")]
        void guardar_datos(string email, string nombre, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icargasql/guardar_datos", ReplyAction="http://tempuri.org/Icargasql/guardar_datosResponse")]
        System.Threading.Tasks.Task guardar_datosAsync(string email, string nombre, string contraseña);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IcargasqlChannel : WebApplication6.ServiceReference2.Icargasql, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IcargasqlClient : System.ServiceModel.ClientBase<WebApplication6.ServiceReference2.Icargasql>, WebApplication6.ServiceReference2.Icargasql {
        
        public IcargasqlClient() {
        }
        
        public IcargasqlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IcargasqlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcargasqlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcargasqlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void guardar_datos(string email, string nombre, string contraseña) {
            base.Channel.guardar_datos(email, nombre, contraseña);
        }
        
        public System.Threading.Tasks.Task guardar_datosAsync(string email, string nombre, string contraseña) {
            return base.Channel.guardar_datosAsync(email, nombre, contraseña);
        }
    }
}
