//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.ServiceReference5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference5.Ipuntajes")]
    public interface Ipuntajes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ipuntajes/guardar_puntajes", ReplyAction="http://tempuri.org/Ipuntajes/guardar_puntajesResponse")]
        void guardar_puntajes(int puntaje, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ipuntajes/guardar_puntajes", ReplyAction="http://tempuri.org/Ipuntajes/guardar_puntajesResponse")]
        System.Threading.Tasks.Task guardar_puntajesAsync(int puntaje, string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IpuntajesChannel : WebApplication6.ServiceReference5.Ipuntajes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IpuntajesClient : System.ServiceModel.ClientBase<WebApplication6.ServiceReference5.Ipuntajes>, WebApplication6.ServiceReference5.Ipuntajes {
        
        public IpuntajesClient() {
        }
        
        public IpuntajesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IpuntajesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IpuntajesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IpuntajesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void guardar_puntajes(int puntaje, string email) {
            base.Channel.guardar_puntajes(puntaje, email);
        }
        
        public System.Threading.Tasks.Task guardar_puntajesAsync(int puntaje, string email) {
            return base.Channel.guardar_puntajesAsync(puntaje, email);
        }
    }
}
