//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.ServiceReference6 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference6.Service1")]
    public interface Service1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/guardar_puntajes", ReplyAction="urn:Service1/guardar_puntajesResponse")]
        void guardar_puntajes(int puntaje, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Service1/guardar_puntajes", ReplyAction="urn:Service1/guardar_puntajesResponse")]
        System.Threading.Tasks.Task guardar_puntajesAsync(int puntaje, string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1Channel : WebApplication6.ServiceReference6.Service1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication6.ServiceReference6.Service1>, WebApplication6.ServiceReference6.Service1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void guardar_puntajes(int puntaje, string email) {
            base.Channel.guardar_puntajes(puntaje, email);
        }
        
        public System.Threading.Tasks.Task guardar_puntajesAsync(int puntaje, string email) {
            return base.Channel.guardar_puntajesAsync(puntaje, email);
        }
    }
}
